"""Model core: parameters, compartments, FOI, dynamics.

Step D 완료: dynamics 는 SEIRV (J 제거) + 4채널 FOI + 백신 동학.
solver.py / runner.py 는 Step E 에서 갱신.
"""

from kt_epimodel_hira.model.dynamics import (
    compute_derivatives,
    make_ode_rhs,
    make_time_varying_ode_rhs,
)
from kt_epimodel_hira.model.foi import (
    assemble_contact_matrix,
    compute_foi,
    compute_foi_home,
    compute_foi_other,
    compute_foi_school,
    compute_foi_work,
    compute_phi_school,
    compute_phi_spillover,
    compute_phi_work,
)
from kt_epimodel_hira.model.mobility_tensor import (
    build_M_from_kt_array,
    build_M_home,
    build_M_other,
    build_M_school,
    build_M_work,
    build_pi_from_kt_array,
    build_pi_tensor,
)
from kt_epimodel_hira.model.compartments import (
    IDX_E,
    IDX_I,
    IDX_R,
    IDX_S,
    IDX_V,
    N_COMPARTMENTS,
    attack_rate,
    attack_rate_by_age,
    attack_rate_total,
    check_conservation,
    flatten_state,
    get_E,
    get_I,
    get_R,
    get_S,
    get_V,
    initial_state,
    total_infectious,
    total_population,
    unflatten_state,
    vaccinated_fraction,
    validate_state,
)
from kt_epimodel_hira.model.parameters import (
    CalibrationParameters,
    DiseaseParameters,
    EmploymentParameters,
    ModelParameters,
    PolicyParameters,
    TimeVaryingParameters,
    VaccinationParameters,
)

__all__ = [
    "CalibrationParameters",
    "DiseaseParameters",
    "EmploymentParameters",
    "IDX_E",
    "IDX_I",
    "IDX_R",
    "IDX_S",
    "IDX_V",
    "ModelParameters",
    "N_COMPARTMENTS",
    "PolicyParameters",
    "TimeVaryingParameters",
    "VaccinationParameters",
    "assemble_contact_matrix",
    "attack_rate",
    "attack_rate_by_age",
    "attack_rate_total",
    "build_M_from_kt_array",
    "build_M_home",
    "build_M_other",
    "build_M_school",
    "build_M_work",
    "build_pi_from_kt_array",
    "build_pi_tensor",
    "check_conservation",
    "compute_derivatives",
    "compute_foi",
    "compute_foi_home",
    "compute_foi_other",
    "compute_foi_school",
    "compute_foi_work",
    "compute_phi_school",
    "compute_phi_spillover",
    "compute_phi_work",
    "flatten_state",
    "get_E",
    "get_I",
    "get_R",
    "get_S",
    "get_V",
    "initial_state",
    "make_ode_rhs",
    "make_time_varying_ode_rhs",
    "total_infectious",
    "total_population",
    "unflatten_state",
    "vaccinated_fraction",
    "validate_state",
]
